export const ELECCION_PRACTICA='ELECCION_PRACTICA'
export const VALIDAR_DATOS='VALIDAR_DATOS'
export const GRAFICA='GRAFICA'
export const DATOS_GRAFICA='DATOS_GRAFICA'
export const DATOS_GRAFICA1='DATOS_GRAFICA1'
export const ACTIVAR_FORMULARIO='ACTIVAR_FORMULARIO'    
export const INICIO_USER='INICIO_USER'   


export const OBTENER_USUARIO='OBTENER_USUARIO'
export const LOGIN_EXITOSO='LOGIN_EXITOSO'
export const LOGIN_ERROR='LOGIN_ERROR'
export const CERRAR_SESION='CERRAR_SESION'

export const    MOSTRAR_ALERTA='MOSTRAR_ALERTA'
export const    OCULTAR_ALERTA='OCULTAR_ALERTA'
